# **SCRAPING DATA ULASAN APLIKASI BCA MOBILE**

# ***SAMPLE***

In [ ]:
#Referensi: https://www.linkedin.com/pulse/how-scrape-google-play-reviews-4-simple-steps-using-python-kundi/

!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.3 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [ ]:
#Scrape desired number of reviews
#Run kode ini jika ingin scrape data dengan jumlah tertentu. Ganti (misal, ingin scrape sejumlah 1000, maka ganti kode , count = 1000 )

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.bca',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=10000,
    filter_score_with=None # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a209ea14-00a7-41f4-ac3d-0bf568d3b42a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,güzel bir banka uygulaması,5,0,4.7.9,2026-04-08 05:52:54,Terima kasih atas ulasannya. Semoga aplikasi B...,2026-04-08 07:12:45,4.7.9
1,6be39a04-9c3c-479b-b287-99946c8b70fb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,dibutuhkan,5,0,4.7.9,2026-04-08 05:47:59,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-08 05:53:57,4.7.9
2,0c263c17-1a94-4506-8402-5c10aab7b49d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,kenapa saya gak bisa memasukkan pin m BCA bbrp...,3,0,4.7.9,2026-04-08 04:51:51,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2026-04-08 04:56:44,4.7.9
3,a764311f-69ec-4359-b1a6-43014c4c968a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"gak sengaja ke teken uninstal,eh pas download ...",1,0,4.7.9,2026-04-08 04:12:36,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, jik...",2026-04-08 04:17:18,4.7.9
4,42adedeb-8558-40e7-abcb-752de501bc23,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tolong evaluasi dibagian jaringan,1,0,4.7.9,2026-04-08 03:05:20,Mohon maaf atas ketidaknyamanannya. Saran dan ...,2026-04-08 03:39:51,4.7.9

In [ ]:
len(df_busu.index) #count the number of data we got

10000

In [ ]:
df_busu[['userName','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

,userName,at,content
0,Pengguna Google,2026-04-08 05:52:54,güzel bir banka uygulaması
1,Pengguna Google,2026-04-08 05:47:59,dibutuhkan
2,Pengguna Google,2026-04-08 04:51:51,kenapa saya gak bisa memasukkan pin m BCA bbrp...
3,Pengguna Google,2026-04-08 04:12:36,"gak sengaja ke teken uninstal,eh pas download ..."
4,Pengguna Google,2026-04-08 03:05:20,tolong evaluasi dibagian jaringan

In [ ]:
#Run This Code to Sort the Data By Date

new_df = df_busu[['userName', 'at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,at,content
0,Pengguna Google,2026-04-08 05:52:54,güzel bir banka uygulaması
1,Pengguna Google,2026-04-08 05:47:59,dibutuhkan
2,Pengguna Google,2026-04-08 04:51:51,kenapa saya gak bisa memasukkan pin m BCA bbrp...
3,Pengguna Google,2026-04-08 04:12:36,"gak sengaja ke teken uninstal,eh pas download ..."
4,Pengguna Google,2026-04-08 03:05:20,tolong evaluasi dibagian jaringan

In [ ]:
my_df = sorted_df[['userName', 'at', 'content']] #get userName, rating, date-time, and reviews only

In [ ]:
my_df.head()

,userName,at,content
0,Pengguna Google,2026-04-08 05:52:54,güzel bir banka uygulaması
1,Pengguna Google,2026-04-08 05:47:59,dibutuhkan
2,Pengguna Google,2026-04-08 04:51:51,kenapa saya gak bisa memasukkan pin m BCA bbrp...
3,Pengguna Google,2026-04-08 04:12:36,"gak sengaja ke teken uninstal,eh pas download ..."
4,Pengguna Google,2026-04-08 03:05:20,tolong evaluasi dibagian jaringan

In [ ]:
my_df.to_csv("scrapped_data_BCA.csv", index = False)  #Save the file as CSV , to download: click the folder icon on the left. the csv file should be there.